name: sa_software

publish_to: 'none'
description: Shahid Autos POS – Flutter (Android, Windows, Web)
version: 0.1.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter: { sdk: flutter }
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  go_router: ^14.2.7

  # Firebase
  firebase_core: ^3.5.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.5.0

  # Local DB (Drift)
  drift: ^2.21.0
  drift_dev: ^2.17.0
  build_runner: ^2.4.6
  drift_flutter: ^0.2.7
  sqlite3_flutter_libs: ^0.5.24
  path_provider: ^2.1.4
  path: ^1.9.0
  web: ^1.1.1

  # Utils
  intl: ^0.19.0
  uuid: ^4.5.0
  connectivity_plus: ^6.0.5
  csv: ^6.0.0
  file_picker: ^8.0.3
  collection: ^1.18.0
  shared_preferences: ^2.3.3

  # Printing
  pdf: ^3.11.0
  printing: ^5.13.4

dev_dependencies:
  flutter_test: { sdk: flutter }
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
